///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ranorex_exercise.PageModules.ViewEditMailPanel
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Set_To_Address recording.
    /// </summary>
    [TestModule("bee505d7-41a4-42cb-9bb8-810b91a836b1", ModuleType.Recording, 1)]
    public partial class Set_To_Address : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ranorex_exercise.Ranorex_exerciseRepository repository.
        /// </summary>
        public static global::Ranorex_exercise.Ranorex_exerciseRepository repo = global::Ranorex_exercise.Ranorex_exerciseRepository.Instance;

        static Set_To_Address instance = new Set_To_Address();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Set_To_Address()
        {
            ToAddress = "test.email@test.test";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Set_To_Address Instance
        {
            get { return instance; }
        }

#region Variables

        string _ToAddress;

        /// <summary>
        /// Gets or sets the value of variable ToAddress.
        /// </summary>
        [TestVariable("d6c6b83d-502e-4f78-9eee-5e70d406a89d")]
        public string ToAddress
        {
            get { return _ToAddress; }
            set { _ToAddress = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MarkAttelerikdomainComMyApplication.ViewEditMailPanel.input_To' at Center.", repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.input_ToInfo, new RecordItemIndex(0));
            repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.input_To.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ToAddress' with focus on 'MarkAttelerikdomainComMyApplication.ViewEditMailPanel.input_To'.", repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.input_ToInfo, new RecordItemIndex(1));
            repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.input_To.PressKeys(ToAddress);
            Delay.Milliseconds(20);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
