///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ranorex_exercise.PageModules.ViewEditMailPanel
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Type_Message recording.
    /// </summary>
    [TestModule("b5cea646-1641-4c87-b66e-eb69e40f250a", ModuleType.Recording, 1)]
    public partial class Type_Message : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ranorex_exercise.Ranorex_exerciseRepository repository.
        /// </summary>
        public static global::Ranorex_exercise.Ranorex_exerciseRepository repo = global::Ranorex_exercise.Ranorex_exerciseRepository.Instance;

        static Type_Message instance = new Type_Message();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Type_Message()
        {
            MessageText = "FYI";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Type_Message Instance
        {
            get { return instance; }
        }

#region Variables

        string _MessageText;

        /// <summary>
        /// Gets or sets the value of variable MessageText.
        /// </summary>
        [TestVariable("f85ea9b0-6b75-4907-9f65-e122f678f823")]
        public string MessageText
        {
            get { return _MessageText; }
            set { _MessageText = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MarkAttelerikdomainComMyApplication.ViewEditMailPanel.edit_MessageBox' at Center.", repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.edit_MessageBoxInfo, new RecordItemIndex(0));
            repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.edit_MessageBox.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Home}{LControlKey up}' with focus on 'MarkAttelerikdomainComMyApplication.ViewEditMailPanel.edit_MessageBox'.", repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.edit_MessageBoxInfo, new RecordItemIndex(1));
            repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.edit_MessageBox.PressKeys("{LControlKey down}{Home}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$MessageText' with focus on 'MarkAttelerikdomainComMyApplication.ViewEditMailPanel.edit_MessageBox'.", repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.edit_MessageBoxInfo, new RecordItemIndex(2));
            repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.edit_MessageBox.PressKeys(MessageText);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}{Return}' with focus on 'MarkAttelerikdomainComMyApplication.ViewEditMailPanel.edit_MessageBox'.", repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.edit_MessageBoxInfo, new RecordItemIndex(3));
            repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.edit_MessageBox.PressKeys("{Return}{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
