///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ranorex_exercise
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Open_Email_By_Click_On_Subject recording.
    /// </summary>
    [TestModule("87244cb1-15b2-4bdc-8bbe-5e9be14c367d", ModuleType.Recording, 1)]
    public partial class Open_Email_By_Click_On_Subject : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Ranorex_exerciseRepository repository.
        /// </summary>
        public static Ranorex_exerciseRepository repo = Ranorex_exerciseRepository.Instance;

        static Open_Email_By_Click_On_Subject instance = new Open_Email_By_Click_On_Subject();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Open_Email_By_Click_On_Subject()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Open_Email_By_Click_On_Subject Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable EmaillSubject.
        /// </summary>
        [TestVariable("f93a521c-909a-4520-a23b-7c85ad22bf2a")]
        public string EmaillSubject
        {
            get { return repo.EmaillSubject; }
            set { repo.EmaillSubject = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MarkAttelerikdomainComMyApplication.MailListPanel.cell_EmailSubject' at 36;33.", repo.MarkAttelerikdomainComMyApplication.MailListPanel.cell_EmailSubjectInfo, new RecordItemIndex(0));
            repo.MarkAttelerikdomainComMyApplication.MailListPanel.cell_EmailSubject.Click("36;33");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
