///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ranorex_exercise
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Ranorex_exerciseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6a3ff6d0-3c9c-4c5a-9f3e-8bdfe058f992")]
    public partial class Ranorex_exerciseRepository : RepoGenBaseFolder
    {
        static Ranorex_exerciseRepository instance = new Ranorex_exerciseRepository();
        Ranorex_exerciseRepositoryFolders.MarkAttelerikdomainComMyApplicationAppFolder _markattelerikdomaincommyapplication;

        /// <summary>
        /// Gets the singleton class instance representing the Ranorex_exerciseRepository element repository.
        /// </summary>
        [RepositoryFolder("6a3ff6d0-3c9c-4c5a-9f3e-8bdfe058f992")]
        public static Ranorex_exerciseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Ranorex_exerciseRepository() 
            : base("Ranorex_exerciseRepository", "/", null, 0, false, "6a3ff6d0-3c9c-4c5a-9f3e-8bdfe058f992", ".\\RepositoryImages\\Ranorex_exerciseRepository6a3ff6d0.rximgres")
        {
            _markattelerikdomaincommyapplication = new Ranorex_exerciseRepositoryFolders.MarkAttelerikdomainComMyApplicationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6a3ff6d0-3c9c-4c5a-9f3e-8bdfe058f992")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MarkAttelerikdomainComMyApplication folder.
        /// </summary>
        [RepositoryFolder("d4a9e1a4-201f-4ee0-b861-7125b6ef7b1d")]
        public virtual Ranorex_exerciseRepositoryFolders.MarkAttelerikdomainComMyApplicationAppFolder MarkAttelerikdomainComMyApplication
        {
            get { return _markattelerikdomaincommyapplication; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Ranorex_exerciseRepositoryFolders
    {
        /// <summary>
        /// The MarkAttelerikdomainComMyApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("d4a9e1a4-201f-4ee0-b861-7125b6ef7b1d")]
        public partial class MarkAttelerikdomainComMyApplicationAppFolder : RepoGenBaseFolder
        {
            Ranorex_exerciseRepositoryFolders.MailPanelFolder _mailpanel;
            Ranorex_exerciseRepositoryFolders.MailListPanelFolder _maillistpanel;

            /// <summary>
            /// Creates a new MarkAttelerikdomainComMyApplication  folder.
            /// </summary>
            public MarkAttelerikdomainComMyApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MarkAttelerikdomainComMyApplication", "/form[@automationid='']", parentFolder, 30000, null, true, "d4a9e1a4-201f-4ee0-b861-7125b6ef7b1d", "")
            {
                _mailpanel = new Ranorex_exerciseRepositoryFolders.MailPanelFolder(this);
                _maillistpanel = new Ranorex_exerciseRepositoryFolders.MailListPanelFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d4a9e1a4-201f-4ee0-b861-7125b6ef7b1d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d4a9e1a4-201f-4ee0-b861-7125b6ef7b1d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MailPanel folder.
            /// </summary>
            [RepositoryFolder("cd22b4e7-03b9-4077-933a-c9c8183d2a68")]
            public virtual Ranorex_exerciseRepositoryFolders.MailPanelFolder MailPanel
            {
                get { return _mailpanel; }
            }

            /// <summary>
            /// The MailListPanel folder.
            /// </summary>
            [RepositoryFolder("a1e8f1de-cfa6-491d-9c24-4cb1a520884e")]
            public virtual Ranorex_exerciseRepositoryFolders.MailListPanelFolder MailListPanel
            {
                get { return _maillistpanel; }
            }
        }

        /// <summary>
        /// The MailPanelFolder folder.
        /// </summary>
        [RepositoryFolder("cd22b4e7-03b9-4077-933a-c9c8183d2a68")]
        public partial class MailPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _treeitem_inboxfolderInfo;

            /// <summary>
            /// Creates a new MailPanel  folder.
            /// </summary>
            public MailPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("MailPanel", "", parentFolder, 0, null, false, "cd22b4e7-03b9-4077-933a-c9c8183d2a68", "")
            {
                _treeitem_inboxfolderInfo = new RepoItemInfo(this, "treeitem_InboxFolder", "?/?/tabpagelist[@automationid='OutlookBar']/button[@automationid='MinimizedContentElement']//container[@automationid='ItemsHost']/?/?/container[@automationid='HeaderContentPanel']/?/?/text[@caption='Inbox']", ".//text[@caption='Inbox']", 30000, null, "597360ac-95e3-455f-915e-a9ae1aa3e7e1");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cd22b4e7-03b9-4077-933a-c9c8183d2a68")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The treeitem_InboxFolder item.
            /// </summary>
            [RepositoryItem("597360ac-95e3-455f-915e-a9ae1aa3e7e1")]
            public virtual Ranorex.Text treeitem_InboxFolder
            {
                get
                {
                    return _treeitem_inboxfolderInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The treeitem_InboxFolder item info.
            /// </summary>
            [RepositoryItemInfo("597360ac-95e3-455f-915e-a9ae1aa3e7e1")]
            public virtual RepoItemInfo treeitem_InboxFolderInfo
            {
                get
                {
                    return _treeitem_inboxfolderInfo;
                }
            }
        }

        /// <summary>
        /// The MailListPanelFolder folder.
        /// </summary>
        [RepositoryFolder("a1e8f1de-cfa6-491d-9c24-4cb1a520884e")]
        public partial class MailListPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _newitemInfo;
            RepoItemInfo _input_searchmailInfo;

            /// <summary>
            /// Creates a new MailListPanel  folder.
            /// </summary>
            public MailListPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("MailListPanel", "", parentFolder, 0, null, false, "a1e8f1de-cfa6-491d-9c24-4cb1a520884e", "")
            {
                _newitemInfo = new RepoItemInfo(this, "NewItem", "element", "element", 30000, null, "16429395-00d4-4453-b2c8-85f98de3194b");
                _input_searchmailInfo = new RepoItemInfo(this, "input_SearchMail", "?/?/tabpagelist[@automationid='OutlookBar']/container[@automationid='MainSectorTemplate']/text/text[@caption='']", ".//text[@automationid='SearchWatermarkTextBox']/text[@caption='']", 30000, null, "4d370a18-c221-49da-8de6-1ec9e14e6488");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a1e8f1de-cfa6-491d-9c24-4cb1a520884e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NewItem item.
            /// </summary>
            [RepositoryItem("16429395-00d4-4453-b2c8-85f98de3194b")]
            public virtual Ranorex.Unknown NewItem
            {
                get
                {
                    return _newitemInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The NewItem item info.
            /// </summary>
            [RepositoryItemInfo("16429395-00d4-4453-b2c8-85f98de3194b")]
            public virtual RepoItemInfo NewItemInfo
            {
                get
                {
                    return _newitemInfo;
                }
            }

            /// <summary>
            /// The input_SearchMail item.
            /// </summary>
            [RepositoryItem("4d370a18-c221-49da-8de6-1ec9e14e6488")]
            public virtual Ranorex.Text input_SearchMail
            {
                get
                {
                    return _input_searchmailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The input_SearchMail item info.
            /// </summary>
            [RepositoryItemInfo("4d370a18-c221-49da-8de6-1ec9e14e6488")]
            public virtual RepoItemInfo input_SearchMailInfo
            {
                get
                {
                    return _input_searchmailInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
