///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ranorex_exercise
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Ranorex_exerciseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6a3ff6d0-3c9c-4c5a-9f3e-8bdfe058f992")]
    public partial class Ranorex_exerciseRepository : RepoGenBaseFolder
    {
        static Ranorex_exerciseRepository instance = new Ranorex_exerciseRepository();
        Ranorex_exerciseRepositoryFolders.MarkAttelerikdomainComMyApplicationAppFolder _markattelerikdomaincommyapplication;

        /// <summary>
        /// Gets the singleton class instance representing the Ranorex_exerciseRepository element repository.
        /// </summary>
        [RepositoryFolder("6a3ff6d0-3c9c-4c5a-9f3e-8bdfe058f992")]
        public static Ranorex_exerciseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Ranorex_exerciseRepository() 
            : base("Ranorex_exerciseRepository", "/", null, 0, false, "6a3ff6d0-3c9c-4c5a-9f3e-8bdfe058f992", ".\\RepositoryImages\\Ranorex_exerciseRepository6a3ff6d0.rximgres")
        {
            _markattelerikdomaincommyapplication = new Ranorex_exerciseRepositoryFolders.MarkAttelerikdomainComMyApplicationAppFolder(this);
        }

#region Variables

        string _EmaillSubject = "How can I";

        /// <summary>
        /// Gets or sets the value of variable EmaillSubject.
        /// </summary>
        [TestVariable("f93a521c-909a-4520-a23b-7c85ad22bf2a")]
        public string EmaillSubject
        {
            get { return _EmaillSubject; }
            set { _EmaillSubject = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6a3ff6d0-3c9c-4c5a-9f3e-8bdfe058f992")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MarkAttelerikdomainComMyApplication folder.
        /// </summary>
        [RepositoryFolder("d4a9e1a4-201f-4ee0-b861-7125b6ef7b1d")]
        public virtual Ranorex_exerciseRepositoryFolders.MarkAttelerikdomainComMyApplicationAppFolder MarkAttelerikdomainComMyApplication
        {
            get { return _markattelerikdomaincommyapplication; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Ranorex_exerciseRepositoryFolders
    {
        /// <summary>
        /// The MarkAttelerikdomainComMyApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("d4a9e1a4-201f-4ee0-b861-7125b6ef7b1d")]
        public partial class MarkAttelerikdomainComMyApplicationAppFolder : RepoGenBaseFolder
        {
            Ranorex_exerciseRepositoryFolders.NewEmailFolder _newemail;
            Ranorex_exerciseRepositoryFolders.MailPanelFolder _mailpanel;
            Ranorex_exerciseRepositoryFolders.MailListPanelFolder _maillistpanel;
            Ranorex_exerciseRepositoryFolders.HomeTabFolder _hometab;
            Ranorex_exerciseRepositoryFolders.ViewEditMailPanelFolder _vieweditmailpanel;

            /// <summary>
            /// Creates a new MarkAttelerikdomainComMyApplication  folder.
            /// </summary>
            public MarkAttelerikdomainComMyApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MarkAttelerikdomainComMyApplication", "/form[@automationid='']", parentFolder, 30000, null, true, "d4a9e1a4-201f-4ee0-b861-7125b6ef7b1d", "")
            {
                _newemail = new Ranorex_exerciseRepositoryFolders.NewEmailFolder(this);
                _mailpanel = new Ranorex_exerciseRepositoryFolders.MailPanelFolder(this);
                _maillistpanel = new Ranorex_exerciseRepositoryFolders.MailListPanelFolder(this);
                _hometab = new Ranorex_exerciseRepositoryFolders.HomeTabFolder(this);
                _vieweditmailpanel = new Ranorex_exerciseRepositoryFolders.ViewEditMailPanelFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d4a9e1a4-201f-4ee0-b861-7125b6ef7b1d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d4a9e1a4-201f-4ee0-b861-7125b6ef7b1d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NewEmail folder.
            /// </summary>
            [RepositoryFolder("b1705d94-cd10-4685-aaaa-002c89350b0e")]
            public virtual Ranorex_exerciseRepositoryFolders.NewEmailFolder NewEmail
            {
                get { return _newemail; }
            }

            /// <summary>
            /// The MailPanel folder.
            /// </summary>
            [RepositoryFolder("cd22b4e7-03b9-4077-933a-c9c8183d2a68")]
            public virtual Ranorex_exerciseRepositoryFolders.MailPanelFolder MailPanel
            {
                get { return _mailpanel; }
            }

            /// <summary>
            /// The MailListPanel folder.
            /// </summary>
            [RepositoryFolder("a1e8f1de-cfa6-491d-9c24-4cb1a520884e")]
            public virtual Ranorex_exerciseRepositoryFolders.MailListPanelFolder MailListPanel
            {
                get { return _maillistpanel; }
            }

            /// <summary>
            /// The HomeTab folder.
            /// </summary>
            [RepositoryFolder("43d81f59-f818-4376-8dc9-2378fad0723d")]
            public virtual Ranorex_exerciseRepositoryFolders.HomeTabFolder HomeTab
            {
                get { return _hometab; }
            }

            /// <summary>
            /// The ViewEditMailPanel folder.
            /// </summary>
            [RepositoryFolder("6a09847e-f0a5-489e-9d21-e9c23718594a")]
            public virtual Ranorex_exerciseRepositoryFolders.ViewEditMailPanelFolder ViewEditMailPanel
            {
                get { return _vieweditmailpanel; }
            }
        }

        /// <summary>
        /// The NewEmailFolder folder.
        /// </summary>
        [RepositoryFolder("b1705d94-cd10-4685-aaaa-002c89350b0e")]
        public partial class NewEmailFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button_sendInfo;
            RepoItemInfo _replyInfo;

            /// <summary>
            /// Creates a new NewEmail  folder.
            /// </summary>
            public NewEmailFolder(RepoGenBaseFolder parentFolder) :
                    base("NewEmail", "", parentFolder, 0, null, false, "b1705d94-cd10-4685-aaaa-002c89350b0e", "")
            {
                _button_sendInfo = new RepoItemInfo(this, "button_Send", "?/?/tabpagelist[@automationid='OutlookBar']/container[@automationid='MainSectorTemplate']/container[2]/container[2]/button", ".//container[@automationid='MainSectorTemplate']/container[2]/container[2]/button", 30000, null, "68aad5b7-6204-4f5a-8f2d-bb845849a800");
                _replyInfo = new RepoItemInfo(this, "Reply", "container[1]/tabpagelist[@automationid='OutlookBar']/container[@automationid='MainSectorTemplate']//button[@text='Reply']", ".//container[@automationid='MainSectorTemplate']/container[2]/container[1]/container[1]/button[@text='Reply']", 30000, null, "d62efb63-5778-4bed-b7c2-a8c26a9e7995");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b1705d94-cd10-4685-aaaa-002c89350b0e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The button_Send item.
            /// </summary>
            [RepositoryItem("68aad5b7-6204-4f5a-8f2d-bb845849a800")]
            public virtual Ranorex.Button button_Send
            {
                get
                {
                    return _button_sendInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The button_Send item info.
            /// </summary>
            [RepositoryItemInfo("68aad5b7-6204-4f5a-8f2d-bb845849a800")]
            public virtual RepoItemInfo button_SendInfo
            {
                get
                {
                    return _button_sendInfo;
                }
            }

            /// <summary>
            /// The Reply item.
            /// </summary>
            [RepositoryItem("d62efb63-5778-4bed-b7c2-a8c26a9e7995")]
            public virtual Ranorex.Button Reply
            {
                get
                {
                    return _replyInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Reply item info.
            /// </summary>
            [RepositoryItemInfo("d62efb63-5778-4bed-b7c2-a8c26a9e7995")]
            public virtual RepoItemInfo ReplyInfo
            {
                get
                {
                    return _replyInfo;
                }
            }
        }

        /// <summary>
        /// The MailPanelFolder folder.
        /// </summary>
        [RepositoryFolder("cd22b4e7-03b9-4077-933a-c9c8183d2a68")]
        public partial class MailPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _treeitem_sendfolderInfo;
            RepoItemInfo _treeitem_inboxfolderInfo;

            /// <summary>
            /// Creates a new MailPanel  folder.
            /// </summary>
            public MailPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("MailPanel", "", parentFolder, 0, null, false, "cd22b4e7-03b9-4077-933a-c9c8183d2a68", "")
            {
                _treeitem_sendfolderInfo = new RepoItemInfo(this, "treeitem_SendFolder", "?/?/tabpagelist[@automationid='OutlookBar']/button[@automationid='MinimizedContentElement']//container[@automationid='ItemsHost']/treeitem[2]/container[@automationid='HeaderContentPanel']/?/?/text[@caption='Sent Items']", ".//text[@caption='Sent Items']", 30000, null, "b9917e8f-be83-447d-b73a-1a97fb0065de");
                _treeitem_inboxfolderInfo = new RepoItemInfo(this, "treeitem_InboxFolder", "?/?/tabpagelist[@automationid='OutlookBar']/button[@automationid='MinimizedContentElement']//container[@automationid='ItemsHost']/?/?/container[@automationid='HeaderContentPanel']/?/?/text[@caption='Inbox']", ".//text[@caption='Inbox']", 30000, null, "597360ac-95e3-455f-915e-a9ae1aa3e7e1");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cd22b4e7-03b9-4077-933a-c9c8183d2a68")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The treeitem_SendFolder item.
            /// </summary>
            [RepositoryItem("b9917e8f-be83-447d-b73a-1a97fb0065de")]
            public virtual Ranorex.Text treeitem_SendFolder
            {
                get
                {
                    return _treeitem_sendfolderInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The treeitem_SendFolder item info.
            /// </summary>
            [RepositoryItemInfo("b9917e8f-be83-447d-b73a-1a97fb0065de")]
            public virtual RepoItemInfo treeitem_SendFolderInfo
            {
                get
                {
                    return _treeitem_sendfolderInfo;
                }
            }

            /// <summary>
            /// The treeitem_InboxFolder item.
            /// </summary>
            [RepositoryItem("597360ac-95e3-455f-915e-a9ae1aa3e7e1")]
            public virtual Ranorex.Text treeitem_InboxFolder
            {
                get
                {
                    return _treeitem_inboxfolderInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The treeitem_InboxFolder item info.
            /// </summary>
            [RepositoryItemInfo("597360ac-95e3-455f-915e-a9ae1aa3e7e1")]
            public virtual RepoItemInfo treeitem_InboxFolderInfo
            {
                get
                {
                    return _treeitem_inboxfolderInfo;
                }
            }
        }

        /// <summary>
        /// The MailListPanelFolder folder.
        /// </summary>
        [RepositoryFolder("a1e8f1de-cfa6-491d-9c24-4cb1a520884e")]
        public partial class MailListPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _input_searchmailInfo;
            RepoItemInfo _cell_emailsubjectInfo;
            RepoItemInfo _howtoaddperpendicularlineintelerikInfo;

            /// <summary>
            /// Creates a new MailListPanel  folder.
            /// </summary>
            public MailListPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("MailListPanel", "", parentFolder, 0, null, false, "a1e8f1de-cfa6-491d-9c24-4cb1a520884e", "")
            {
                _input_searchmailInfo = new RepoItemInfo(this, "input_SearchMail", "?/?/tabpagelist[@automationid='OutlookBar']/container[@automationid='MainSectorTemplate']/text/text[@caption='']", ".//text[@automationid='SearchWatermarkTextBox']/text[@caption='']", 30000, null, "4d370a18-c221-49da-8de6-1ec9e14e6488");
                _cell_emailsubjectInfo = new RepoItemInfo(this, "cell_EmailSubject", ".//table[@automationid='gridView']/?/?/?/list[@automationid='PART_DataCellsPresenter']/cell[@text>$EmaillSubject]", "", 30000, null, "66a918c2-dbd2-4981-a0b0-862189f9fccc");
                _howtoaddperpendicularlineintelerikInfo = new RepoItemInfo(this, "HowToAddPerpendicularLineInTelerik", ".//table[@automationid='gridView']/container[@automationid='PART_ItemsScrollViewer']/container[@automationid='PART_GridViewVirtualizingPanel']/?/?/cell[@text>'How to Add']", "", 30000, null, "6d598557-f76d-4996-8cec-08ec9e6511ab");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a1e8f1de-cfa6-491d-9c24-4cb1a520884e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The input_SearchMail item.
            /// </summary>
            [RepositoryItem("4d370a18-c221-49da-8de6-1ec9e14e6488")]
            public virtual Ranorex.Text input_SearchMail
            {
                get
                {
                    return _input_searchmailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The input_SearchMail item info.
            /// </summary>
            [RepositoryItemInfo("4d370a18-c221-49da-8de6-1ec9e14e6488")]
            public virtual RepoItemInfo input_SearchMailInfo
            {
                get
                {
                    return _input_searchmailInfo;
                }
            }

            /// <summary>
            /// The cell_EmailSubject item.
            /// </summary>
            [RepositoryItem("66a918c2-dbd2-4981-a0b0-862189f9fccc")]
            public virtual Ranorex.Cell cell_EmailSubject
            {
                get
                {
                    return _cell_emailsubjectInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The cell_EmailSubject item info.
            /// </summary>
            [RepositoryItemInfo("66a918c2-dbd2-4981-a0b0-862189f9fccc")]
            public virtual RepoItemInfo cell_EmailSubjectInfo
            {
                get
                {
                    return _cell_emailsubjectInfo;
                }
            }

            /// <summary>
            /// The HowToAddPerpendicularLineInTelerik item.
            /// </summary>
            [RepositoryItem("6d598557-f76d-4996-8cec-08ec9e6511ab")]
            public virtual Ranorex.Cell HowToAddPerpendicularLineInTelerik
            {
                get
                {
                    return _howtoaddperpendicularlineintelerikInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The HowToAddPerpendicularLineInTelerik item info.
            /// </summary>
            [RepositoryItemInfo("6d598557-f76d-4996-8cec-08ec9e6511ab")]
            public virtual RepoItemInfo HowToAddPerpendicularLineInTelerikInfo
            {
                get
                {
                    return _howtoaddperpendicularlineintelerikInfo;
                }
            }
        }

        /// <summary>
        /// The HomeTabFolder folder.
        /// </summary>
        [RepositoryFolder("43d81f59-f818-4376-8dc9-2378fad0723d")]
        public partial class HomeTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button_replyInfo;

            /// <summary>
            /// Creates a new HomeTab  folder.
            /// </summary>
            public HomeTabFolder(RepoGenBaseFolder parentFolder) :
                    base("HomeTab", "", parentFolder, 0, null, false, "43d81f59-f818-4376-8dc9-2378fad0723d", "")
            {
                _button_replyInfo = new RepoItemInfo(this, "button_Reply", ".//tabpage[@title='Home']/button[@name='CollapsedButton' and @text='Respond']/?/?/button[@text='Reply']", ".//button[@text='Reply']", 30000, null, "a2854dda-c5f0-435e-baec-83e17d6b0447");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("43d81f59-f818-4376-8dc9-2378fad0723d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The button_Reply item.
            /// </summary>
            [RepositoryItem("a2854dda-c5f0-435e-baec-83e17d6b0447")]
            public virtual Ranorex.Button button_Reply
            {
                get
                {
                    return _button_replyInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The button_Reply item info.
            /// </summary>
            [RepositoryItemInfo("a2854dda-c5f0-435e-baec-83e17d6b0447")]
            public virtual RepoItemInfo button_ReplyInfo
            {
                get
                {
                    return _button_replyInfo;
                }
            }
        }

        /// <summary>
        /// The ViewEditMailPanelFolder folder.
        /// </summary>
        [RepositoryFolder("6a09847e-f0a5-489e-9d21-e9c23718594a")]
        public partial class ViewEditMailPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _sometext1Info;
            RepoItemInfo _sometextInfo;

            /// <summary>
            /// Creates a new ViewEditMailPanel  folder.
            /// </summary>
            public ViewEditMailPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("ViewEditMailPanel", "", parentFolder, 0, null, false, "6a09847e-f0a5-489e-9d21-e9c23718594a", "")
            {
                _sometext1Info = new RepoItemInfo(this, "SomeText1", ".//container[@automationid='MainSectorTemplate']/?/?/container[@automationid='editableRichTextBox']/container[@automationid='ViewPresenter']/container[@automationid='LinesDocumentLayer']/text[4]", ".//container[@automationid='LinesDocumentLayer']/text[4]", 30000, null, "cc91bb28-e964-4ae4-aa25-fd112a2ccdbb");
                _sometextInfo = new RepoItemInfo(this, "SomeText", ".//container[@automationid='MainSectorTemplate']/?/?/container[@automationid='editableRichTextBox']/container[@automationid='ViewPresenter']/container[@automationid='LinesDocumentLayer']/text[2]", ".//container[@automationid='LinesDocumentLayer']/text[2]", 30000, null, "e47fa634-0f17-4693-baef-0cc70f17a181");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6a09847e-f0a5-489e-9d21-e9c23718594a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeText1 item.
            /// </summary>
            [RepositoryItem("cc91bb28-e964-4ae4-aa25-fd112a2ccdbb")]
            public virtual Ranorex.Text SomeText1
            {
                get
                {
                    return _sometext1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText1 item info.
            /// </summary>
            [RepositoryItemInfo("cc91bb28-e964-4ae4-aa25-fd112a2ccdbb")]
            public virtual RepoItemInfo SomeText1Info
            {
                get
                {
                    return _sometext1Info;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("e47fa634-0f17-4693-baef-0cc70f17a181")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("e47fa634-0f17-4693-baef-0cc70f17a181")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
