///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ranorex_exercise
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ReplyOnMail recording.
    /// </summary>
    [TestModule("715a4290-40cd-46fc-be8f-f8a13835546e", ModuleType.Recording, 1)]
    public partial class ReplyOnMail : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Ranorex_exerciseRepository repository.
        /// </summary>
        public static Ranorex_exerciseRepository repo = Ranorex_exerciseRepository.Instance;

        static ReplyOnMail instance = new ReplyOnMail();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ReplyOnMail()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ReplyOnMail Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MarkAttelerikdomainComMyApplication.MailPanel.treeitem_InboxFolder' at Center.", repo.MarkAttelerikdomainComMyApplication.MailPanel.treeitem_InboxFolderInfo, new RecordItemIndex(0));
            repo.MarkAttelerikdomainComMyApplication.MailPanel.treeitem_InboxFolder.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MarkAttelerikdomainComMyApplication.MailListPanel.input_SearchMail' at 286;10.", repo.MarkAttelerikdomainComMyApplication.MailListPanel.input_SearchMailInfo, new RecordItemIndex(1));
            repo.MarkAttelerikdomainComMyApplication.MailListPanel.input_SearchMail.Click("286;10");
            Delay.Milliseconds(2170);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'How can i' with focus on 'MarkAttelerikdomainComMyApplication.MailListPanel.input_SearchMail'.", repo.MarkAttelerikdomainComMyApplication.MailListPanel.input_SearchMailInfo, new RecordItemIndex(2));
            repo.MarkAttelerikdomainComMyApplication.MailListPanel.input_SearchMail.PressKeys("How can i");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MarkAttelerikdomainComMyApplication.MailListPanel.HowCanIImplementFiletringBehavior' at 36;33.", repo.MarkAttelerikdomainComMyApplication.MailListPanel.HowCanIImplementFiletringBehaviorInfo, new RecordItemIndex(3));
            repo.MarkAttelerikdomainComMyApplication.MailListPanel.HowCanIImplementFiletringBehavior.Click("36;33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='In all versions of Telerik controls released in 2013 the ability to implement custom FilteringBehavior for RadAutoCompleteBox is available') on item 'MarkAttelerikdomainComMyApplication.ViewEditMailPanel.SomeText1'.", repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.SomeText1Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.SomeText1Info, "Text", "In all versions of Telerik controls released in 2013 the ability to implement custom FilteringBehavior for RadAutoCompleteBox is available");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MarkAttelerikdomainComMyApplication.HomeTab.button_Reply' at 11;9.", repo.MarkAttelerikdomainComMyApplication.HomeTab.button_ReplyInfo, new RecordItemIndex(5));
            repo.MarkAttelerikdomainComMyApplication.HomeTab.button_Reply.Click("11;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MarkAttelerikdomainComMyApplication.NewEmail.button_Send' at 16;23.", repo.MarkAttelerikdomainComMyApplication.NewEmail.button_SendInfo, new RecordItemIndex(6));
            repo.MarkAttelerikdomainComMyApplication.NewEmail.button_Send.Click("16;23");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
