///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ranorex_exercise
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Search_Email_By_Subject recording.
    /// </summary>
    [TestModule("9fcae4e3-c7a8-41a7-a52d-6de136ead007", ModuleType.Recording, 1)]
    public partial class Search_Email_By_Subject : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Ranorex_exerciseRepository repository.
        /// </summary>
        public static Ranorex_exerciseRepository repo = Ranorex_exerciseRepository.Instance;

        static Search_Email_By_Subject instance = new Search_Email_By_Subject();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Search_Email_By_Subject()
        {
            SearchValue = "How can i";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Search_Email_By_Subject Instance
        {
            get { return instance; }
        }

#region Variables

        string _SearchValue;

        /// <summary>
        /// Gets or sets the value of variable SearchValue.
        /// </summary>
        [TestVariable("efc2416b-3cfd-4f0f-bb18-7293134d9a9d")]
        public string SearchValue
        {
            get { return _SearchValue; }
            set { _SearchValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MarkAttelerikdomainComMyApplication.MailListPanel.input_SearchMail' at 286;10.", repo.MarkAttelerikdomainComMyApplication.MailListPanel.input_SearchMailInfo, new RecordItemIndex(0));
            repo.MarkAttelerikdomainComMyApplication.MailListPanel.input_SearchMail.Click("286;10");
            Delay.Milliseconds(2170);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$SearchValue' with focus on 'MarkAttelerikdomainComMyApplication.MailListPanel.input_SearchMail'.", repo.MarkAttelerikdomainComMyApplication.MailListPanel.input_SearchMailInfo, new RecordItemIndex(1));
            repo.MarkAttelerikdomainComMyApplication.MailListPanel.input_SearchMail.PressKeys(SearchValue);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
