///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ranorex_exercise
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validate_Email_Message_Content recording.
    /// </summary>
    [TestModule("e9c93f92-a3b3-4971-b73f-07aef07cba7d", ModuleType.Recording, 1)]
    public partial class Validate_Email_Message_Content : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Ranorex_exerciseRepository repository.
        /// </summary>
        public static Ranorex_exerciseRepository repo = Ranorex_exerciseRepository.Instance;

        static Validate_Email_Message_Content instance = new Validate_Email_Message_Content();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validate_Email_Message_Content()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validate_Email_Message_Content Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='In all versions of Telerik controls released in 2013 the ability to implement custom FilteringBehavior for RadAutoCompleteBox is available') on item 'MarkAttelerikdomainComMyApplication.ViewEditMailPanel.SomeText1'.", repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.SomeText1Info, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.SomeText1Info, "Text", "In all versions of Telerik controls released in 2013 the ability to implement custom FilteringBehavior for RadAutoCompleteBox is available");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
