///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ranorex_exercise
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validate_Email_Subject recording.
    /// </summary>
    [TestModule("7de4455a-c487-4b88-8dff-c9b0636c1d23", ModuleType.Recording, 1)]
    public partial class Validate_Email_Subject : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Ranorex_exerciseRepository repository.
        /// </summary>
        public static Ranorex_exerciseRepository repo = Ranorex_exerciseRepository.Instance;

        static Validate_Email_Subject instance = new Validate_Email_Subject();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validate_Email_Subject()
        {
            ControlValue = "FW: How can I implement \"FiletringBehavior\" ?";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validate_Email_Subject Instance
        {
            get { return instance; }
        }

#region Variables

        string _ControlValue;

        /// <summary>
        /// Gets or sets the value of variable ControlValue.
        /// </summary>
        [TestVariable("9d97a1f2-193f-4bc8-a150-27ef2e5000a8")]
        public string ControlValue
        {
            get { return _ControlValue; }
            set { _ControlValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$ControlValue) on item 'MarkAttelerikdomainComMyApplication.ViewEditMailPanel.input_Subject'.", repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.input_SubjectInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.MarkAttelerikdomainComMyApplication.ViewEditMailPanel.input_SubjectInfo, "Text", ControlValue);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
